apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projecttemplate

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Add labels to all resources
commonLabels:
  app.kubernetes.io/name: projecttemplate-api
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize

# Customize ConfigMap
configMapGenerator:
  - name: projecttemplate-api-config
    behavior: merge
